/**
 * Generates default config classpath resources from `@Config` annotations.
 *
 * Output layout mirrors runtime resolution:
 *   locus/config/defaults/<name>.jsonc
 *   locus/config/defaults/ext/<extensionId>/<name>.jsonc
 *
 * Full classpath annotation scanning lands with KSP; this plugin wires the
 * output directory and a placeholder task so modules can depend on it now.
 *
 * ```
 * plugins {
 *   id("capital.yuri.locus.config-resources")
 * }
 *
 * locusConfigResources {
 *   enabled.set(true)
 * }
 * ```
 */
interface LocusConfigResourcesExtension {
    val enabled: Property<Boolean>
    /** Relative resource root under generated output (default locus/config/defaults). */
    val resourceRoot: Property<String>
}

val locusConfigResources =
    extensions.create<LocusConfigResourcesExtension>("locusConfigResources")

locusConfigResources.enabled.convention(true)
locusConfigResources.resourceRoot.convention("locus/config/defaults")

val generatedConfigResources =
    layout.buildDirectory.dir("generated/locus-config-resources")

val generateConfigResources by tasks.registering {
    val enabled = locusConfigResources.enabled
    val resourceRoot = locusConfigResources.resourceRoot
    val outputDir = generatedConfigResources

    outputs.dir(outputDir)

    doLast {
        if (!enabled.get()) return@doLast
        val root = outputDir.get().asFile.resolve(resourceRoot.get())
        root.mkdirs()
        // Marker so processResources always has a stable directory.
        // Annotation-driven emission (encodeDefaults from @Config types) is next.
        val readme = root.resolve(".generated")
        if (!readme.exists()) {
            readme.writeText(
                "Generated by capital.yuri.locus.config-resources — " +
                    "defaults will be emitted from @Config types.\n",
            )
        }
    }
}

plugins.withId("java") {
    extensions.configure<SourceSetContainer>("sourceSets") {
        named("main") {
            resources.srcDir(generatedConfigResources)
        }
    }
    tasks.named("processResources") {
        dependsOn(generateConfigResources)
    }
}
